### ISSUE TITLE
Address and waste data not found

### ISSUE THREAD

**Issue by Jacob-nr5** [pippyn/Home-Assistant-Sensor-Afvalbeheer#505] opened 2024-08-27 14:23 UTC
No data after the last upgrade HA to 2024.8,
Current installed versions
HA: 2024.8.3
Afvalbeheer 5.3.8
HACS 2.0.0

HA Log:
2024-08-27 16:12:26.064 ERROR (SyncWorker_5) [custom_components.afvalbeheer.API] Address not found!
2024-08-27 16:12:26.127 ERROR (MainThread) [custom_components.afvalbeheer.API] No Waste data found!
-----

Config:
##### Afvalbeheer #####
afvalbeheer:
  wastecollector: Meppel
  resources:
    - gft
    - papier
    - pmd
  postcode: 7943RK
  streetnumber: 4
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 1 
  nameprefix: 1 
  builtinicons: 1
  dutch: 1

**Comment by pippyn** [comment] 2024-08-27 14:24
Duplicate of #503

**Comment by Jacob-nr5** [comment] 2024-08-27 15:11
#503 is closed, but I still have the same errror.

**Comment by Goz3rr** [comment] 2024-08-27 21:48
This is not a duplicate of #503, Meppel has changed apps to MijnAfvalwijzer since [the 1st of august](https://www.rtvmeppel.nl/bestaande-afvalapp-wordt-straks-niet-meer-bijgewerkt/). Changing from `wastecollector: Meppel` to `wastecollector: MijnAfvalwijzer` works as a workaround.

The only thing I noticed is on the new platform HA no longer has a 'vet' resource, and enabling `printwastetypes: 1` also only shows 'GFT, Papier, PMD'. I suspect the new resource is now called 'keukenafval'

**Comment by pippyn** [comment] 2024-08-28 06:50
You are right. I'm sorry.
It's not a workaround, it's a fix. But it will create new entities in most cases.

**Comment by Jacob-nr5** [comment] 2024-08-28 06:56
@pippyn, thanks for all the hardwork and creating of the new entities.
Now the "vetgoed"is seen as "GTF", the other seems good

@Goz3rr, you are right, thanks. I changed meppel to mijnafvalwijzer and I got new working sensors again. :-)

**Comment by pippyn** [comment] 2024-08-28 07:01
@Jacob-nr5 Can you give me your config (with an address) so I can do some tests?

**Comment by Jacob-nr5** [comment] 2024-08-28 07:14
The new config.
The old config is in the top of this page.
##### Afvalbeheer #####
afvalbeheer:
  wastecollector: mijnafvalwijzer
  resources:
    - gft
    - papier
    - pmd
  postcode: 7943RK
  streetnumber: 4
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 1 
  nameprefix: 1 
  builtinicons: 1
  dutch: 1
##### Einde Afvalbeheer #####

**Comment by pippyn** [comment] 2024-08-28 07:27
The issue is that the fraction `VET-goed` is specific to Meppel, where they refer to it using the code `keukenafval`. Therefore, it will be mapped to `GFT`.

**Comment by Goz3rr** [comment] 2024-08-28 07:43
I think it definitely should not be GFT, as explained [here](https://www.meppel.nl/Inwoner/Afval_groen/Soorten_afval/Inzameling_vet_goede) it's frying oil, electrical devices and textiles.

> VET-goed (vetten, elektrische apparaten, textiel)
De gemeente haalt Vetten (frituurvet en -olie), Elektrische apparaten (tot 10 kg) en Textiel bij u thuis op. Raadpleeg hiervoor de Afvalkalender.

**Comment by pippyn** [comment] 2024-08-28 07:47
I understand. But Meppel uses the wrong code for this fraction, namely `keukenafval`. If I change this mapping a lot of other people will see `VET-goed` when it should be `GFT`. I'm not sure how I'm able to fix this.

**Comment by pippyn** [comment] 2024-08-28 08:00
That is a really hacky solution, I'll find a better way

**Comment by Goz3rr** [comment] 2024-08-28 08:44
I suppose, this is what I did locally so I didn't have to change the config, it didn't create new entities and I didn't have to modify any automations.

If you don't find a better solution let me know and I can throw this in a PR.

```patch
diff --git custom_components/afvalbeheer/API.py custom_components/afvalbeheer/API.py
index 281c324..8fea3f8 100644
--- custom_components/afvalbeheer/API.py
+++ custom_components/afvalbeheer/API.py
@@ -114,7 +114,7 @@ class WasteData(object):
     def __select_collector(self):
         if self.waste_collector in XIMMIO_COLLECTOR_IDS.keys():
             self.collector = XimmioCollector(self.hass, self.waste_collector, self.postcode, self.street_number, self.suffix, self.address_id, self.customer_id)
-        elif self.waste_collector in ["mijnafvalwijzer", "afvalstoffendienstkalender", "rova"]:
+        elif self.waste_collector in ["mijnafvalwijzer", "afvalstoffendienstkalender", "rova", "meppel"]:
             self.collector = AfvalwijzerCollector(self.hass, self.waste_collector, self.postcode, self.street_number, self.suffix)
         elif self.waste_collector == "afvalalert":
             self.collector = AfvalAlertCollector(self.hass, self.waste_collector, self.postcode, self.street_number, self.suffix)
@@ -275,6 +275,9 @@ class AfvalwijzerCollector(WasteCollector):
         self.apikey = '5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca'
         if self.waste_collector == "rova":
             self.waste_collector_url = "inzamelkalender." + self.waste_collector
+        elif self.waste_collector == "meppel":
+            self.WASTE_TYPE_MAPPING['keukenafval'] = WASTE_TYPE_VETGOED
+            self.waste_collector_url = "mijnafvalwijzer"
         else:
             self.waste_collector_url = self.waste_collector

diff --git custom_components/afvalbeheer/const.py custom_components/afvalbeheer/const.py
index 1d3f97b..86c10e1 100644
--- custom_components/afvalbeheer/const.py
+++ custom_components/afvalbeheer/const.py
@@ -111,7 +111,6 @@ XIMMIO_COLLECTOR_IDS = {
     'hellendoorn':      '24434f5b-7244-412b-9306-3a2bd1e22bc1',
     'meerlanden':       '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45',
     'ximmio':           '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45',
-    'meppel':           'b7a594c7-2490-4413-88f9-94749a3ec62a',
     'rad':              '13a2cad9-36d0-4b01-b877-efcb421a864d',
     'twentemilieu':     '8d97bb56-5afd-4cbc-a651-b4f7314264b4',
     'waardlanden':      '942abcf6-3775-400d-ae5d-7380d728b23c',
@@ -156,6 +155,7 @@ WASTE_TYPE_REMAINDER = 'Restwagen'
 WASTE_TYPE_TEXTILE = 'Textiel'
 WASTE_TYPE_TREE = 'Kerstbomen'
 WASTE_TYPE_BULKYGARDENWASTE = 'Tuinafval'
+WASTE_TYPE_VETGOED = 'Vet'

 FRACTION_ICONS = {
     'gft':              'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8IS0tIENyZWF0b3I6IENvcmVsRFJBVyBYNiAtLT4NCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWw6c3BhY2U9InByZXNlcnZlIiB3aWR0aD0iNS4zMzMzM2luIiBoZWlnaHQ9IjUuMzMzMzNpbiIgdmVyc2lvbj0iMS4xIiBzdHlsZT0ic2hhcGUtcmVuZGVyaW5nOmdlb21ldHJpY1ByZWNpc2lvbjsgdGV4dC1yZW5kZXJpbmc6Z2VvbWV0cmljUHJlY2lzaW9uOyBpbWFnZS1yZW5kZXJpbmc6b3B0aW1pemVRdWFsaXR5OyBmaWxsLXJ1bGU6ZXZlbm9kZDsgY2xpcC1ydWxlOmV2ZW5vZGQiDQp2aWV3Qm94PSIwIDAgNTMzMyA1MzMzIg0KIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4NCiA8ZGVmcz4NCiAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCiAgIDwhW0NEQVRBWw0KICAgIC5zdHIwIHtzdHJva2U6IzIzMUYyMDtzdHJva2Utd2lkdGg6MTExLjExfQ0KICAgIC5maWwwIHtmaWxsOm5vbmU7ZmlsbC1ydWxlOm5vbnplcm99DQogICBdXT4NCiAgPC9zdHlsZT4NCiA8L2RlZnM+DQogPGcgaWQ9IkxheWVyX3gwMDIwXzEiPg0KICA8bWV0YWRhdGEgaWQ9IkNvcmVsQ29ycElEXzBDb3JlbC1MYXllciIvPg0KICA8cGF0aCBjbGFzcz0iZmlsMCBzdHIwIiBkPSJNNTI3NSAyNjY1YzAsMTQ0MSAtMTE2OCwyNjEwIC0yNjEwLDI2MTAgLTE0NDEsMCAtMjYxMCwtMTE2OCAtMjYxMCwtMjYxMCAwLC0xNDQxIDExNjgsLTI2MTAgMjYxMCwtMjYxMCAxNDQxLDAgMjYxMCwxMTY4IDI2MTAsMjYxMHptMCAweiIvPg0KICA8cGF0aCBjbGFzcz0iZmlsMCBzdHIwIiBkPSJNMzEwOSAyMjQ4YzAsMCAtNTEzLDQzNyAtMTg2LDEwOTMgMTA3LDIxMyAxOTUsMzQ0IDI2NSw0MjQiLz4NCiAgPHBhdGggY2xhc3M9ImZpbDAgc3RyMCIgZD0iTTE5NzggMzY1MGM4NDMsLTcyOCAtNTksLTE2MzEgLTU5LC0xNjMxIi8+DQogIDxwYXRoIGNsYXNzPSJmaWwwIHN0cjAiIGQ9Ik0yMzY3IDIxNjBjMCwwIDMyNyw4NjMgLTg3LDE1MTkiLz4NCiAgPHBhdGggY2xhc3M9ImZpbDAgc3RyMCIgZD0iTTI5NTQgMzc1MWMtMTU5LC0xNzMgLTUzMiwtNjI5IC00MDEsLTk2OCA3NSwtMTk1IDI4NCwtNDM0IDQwMiwtNTY0Ii8+DQogIDxwYXRoIGNsYXNzPSJmaWwwIHN0cjAiIGQ9Ik0yOTk1IDIxNzFjLTE1MCwtODIgLTQwNSwtMTYxIC03MDYsMzAgLTExLDAgLTY4OSwtMzcwIC05NDAsLTE5NiAtMjUxLDE3NCAxNzUsLTE5NiAxNzUsLTE5NiAwLDAgNjgxLC00NjYgMTIxNCwtMzkgNyw2IDE0LDEyIDIxLDE4IDExLDAgNjU2LC01MTIgMTE2OSwyMiAtMTEsMCAtNzMyLDY1IC03ODcsNDU3IC00LDQgLTU3LC00NiAtMTQ3LC05NnoiLz4NCiAgPHBhdGggY2xhc3M9ImZpbDAgc3RyMCIgZD0iTTE1NjkgMzgxMmMxMzEsMTIwIDQyNiw1NDQgMTAyNyw3NiAwLDAgNDkyLDQ0NiAxMDM4LDEzMCAtMTEsMCAyOTUsLTc2IDQwNCwtNDM1IC03NywzMyAtMjQwLDI1MCAtNjAxLDEyMCAwLDAgLTQwNCwyNjEgLTcyMSwtMTA5IDAsLTIyIC00OTIsMTc0IC02OTksMCAwLC0xMSAtMzE3LDIzOSAtNTc5LC00MyAwLDAgMCwxNDEgMTMxLDI2MXptMCAweiIvPg0KICA8cGF0aCBjbGFzcz0iZmlsMCBzdHIwIiBkPSJNMzQ3MCAxMDk4YzAsMCAtNzA5LDE0MiAtNjk4LDYzMyAtMTEsMCAtMjI5LC0yNzMgNjExLC04MjlsODcgMTk2em0wIDB6Ii8+DQogPC9nPg0KPC9zdmc+DQo=',

```

**Comment by pippyn** [comment] 2024-09-06 12:20
Version v5.4.0 adds a new option named `custommapping` for providing your own fraction mapping.
So this config will work for VET-goed:
```
afvalbeheer:
  - wastecollector: mijnafvalwijzer
    resources:
      - GFT
      - Papier
      - PMD
      - VET-goed
    postcode: 7943RK
    streetnumber: 4
    custommapping:
      keukenafval: VET-goed
```

**Comment by Jacob-nr5** [comment] 2024-09-08 08:45
> Version v5.4.0 adds a new option named `custommapping` for providing your own fraction mapping. So this config will work for VET-goed:
> 
> ```
> afvalbeheer:
>   - wastecollector: mijnafvalwijzer
>     resources:
>       - GFT
>       - Papier
>       - PMD
>       - VET-goed
>     postcode: 7943RK
>     streetnumber: 4
>     custommapping:
>       keukenafval: VET-goed
> ```

Thanks, this is working. :-)

**Closed** 2024-09-09 06:48 UTC
