### ISSUE TITLE
Afvalbeheer stopped working after last update

### ISSUE THREAD

**Issue by menloperk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#504] opened 2024-08-27 14:10 UTC
See title

**Comment by menloperk** [comment] 2024-08-27 14:11
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:942
First occurred: 4:06:34 PM (20 occurrences)
Last logged: 4:11:04 PM

Update for sensor.restafval fails
Update for sensor.pmd fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/sensor.py", line 124, in update
    self.__set_state(collection)
  File "/config/custom_components/afvalbeheer/sensor.py", line 146, in __set_state
    self._state = collection.date.strftime(date_format)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strftime() argument 1 must be str, not None

**Comment by pippyn** [comment] 2024-08-27 14:12
Duplicate of #503

**Closed as completed by pippyn** 2024-08-27 14:12 UTC
