### ISSUE TITLE
RD4 Unknown

### ISSUE THREAD

**Issue by renejorissen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#297] opened 2022-02-03 10:26 UTC
Since last week all sensor give "unknown" as output. My configuration:

  - platform: afvalbeheer
    wastecollector: rd4
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 6343CL
    streetnumber: 1
    upcomingsensor: 1
    dateformat: '%d-%m-%Y'
    alwaysshowday: 1
    dutch: 1
    updateinterval: 24

When I test the JSON URL, I see output for the different containers and collection dates.
[https://rd4.syzygy.eu/6343CL/1/]

I see the following in the logs after a HA restart.
_"2022-02-03 11:23:25 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"
"2022-02-03 11:23:35 ERROR (MainThread) [custom_components.afvalbeheer.sensor] Error occurred while fetching data: JSONDecodeError('Expecting value', '')"_

**Comment by pippyn** [comment] 2022-02-03 10:30
I would recommend you set a higher [update interval](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval), like 12 or 24. This API has the tendency to block ip's for too many requests. After you've set the option and restarted HA it should work again after a couple of days.

**Comment by renejorissen** [comment] 2022-02-03 13:57
The updateinterval is already set to 24h. I would expect that I cannot access the JSON API from my laptop when they block IP's for too many request, since my laptop and HA are on the same network and access the internet with the same public IP.

**Comment by pippyn** [comment] 2022-02-03 16:34
I think it's not only based on your ip.. I just noticed the rate limit is only 5, so if you reboot HA a couple of times you've already reached the limit..
I'm looking for a better data source, but so far no luck..

**Comment by renejorissen** [comment] 2022-02-03 16:44
Thanks!! I will just wait and see if the connections comes back up. Do you have an idea what the block period is?

**Comment by Scriptman** [comment] 2022-03-18 09:38
@renejorissen I'm having the same problem.. when navigating to the website i get a 403 error (it's almost 4 months like that)..
I don't like the use of third-party websites, maybe it's better to implement RD4 directly:
https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public_text.aspx?pc=6372GJ&nr=10&t=

**Comment by pippyn** [comment] 2022-03-18 10:11
Would be better indeed, but the don't have an API. At least I can't find it.

**Comment by Untiring** [comment] 2022-04-19 08:16
im having the same issue as OP described. calling the https://rd4.syzygy.eu/<POSTCODE>/<HUISNUMMER> api manually returns a 403 error. update interval is set to 12, it has never worked for me

**Comment by malosaa** [comment] 2022-04-24 08:11
> im having the same issue as OP described. calling the https://rd4.syzygy.eu// api manually returns a 403 error. update interval is set to 12, it has never worked for me

Just try it with a vpn and see if it work.
For i requested a ip change and its solved.. 

That rd4.syzygy is not official, its just from one of the it workers they build it.
I did call theyr IT department and claim not to have an api, when i mentioned this they said its home made.

I have this url for years, but you get blocked really easy if u do to much requests

**Comment by malosaa** [comment] 2022-04-24 08:16
@pippyn 

Is there a way to make it a daily update? 
like changing this SCHEDULE_UPDATE_INTERVAL = timedelta(hours=1)

I would like to let it update 00:00.
Or is there an automation to call your add-on to let it update again.

Regards

**Comment by pippyn** [comment] 2022-04-25 06:18
@malosaa yes you can with the[ update interval option](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval)

**Comment by malosaa** [comment] 2022-04-25 10:45
Thanks

**Comment by pippyn** [comment] 2022-06-21 12:54
v4.9.3 of the sensor should fix all problems with RD4. 
Could you all please verify?

**Comment by pippyn** [comment] 2022-06-21 13:15
v4.9.4 should fix this issue

**Comment by Untiring** [comment] 2022-06-21 13:29
updated, Papier sensor still unknown (other sensors' values have been updated and are working)

**Comment by pippyn** [comment] 2022-06-21 13:30
Could you DM me your config including your address on the HA forum?
[This is me](https://community.home-assistant.io/u/pippyn)

**Comment by Scriptman** [comment] 2022-06-22 13:11
@pippyn thank you very much, did not tested it yet.

**Comment by Untiring** [comment] 2022-06-22 13:17
> Could you DM me your config including your address on the HA forum? [This is me](https://community.home-assistant.io/u/pippyn)

maybe a stupid question, but i don't see an option on your profile page to DM you, am i missing something?

**Comment by pippyn** [comment] 2022-06-22 13:32
If you're logged in you should see it here
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/7591990/175041534-1fcc92b1-be22-4ac0-94ac-56967dc57f75.png">

**Comment by pippyn** [comment] 2022-06-22 14:12
Is it a new account? Because you may lack the rights to start a conversation.

Could you post your config here, but change the address details to a random house in your neighborhood?

**Comment by pippyn** [comment] 2022-06-22 14:35
> upcomingsensor: 7

BTW `upcomingsensor` should be 1 or 0. (like in true or false)

**Comment by Untiring** [comment] 2022-06-22 14:54
![image](https://user-images.githubusercontent.com/19589238/175060544-297ed35e-9f4e-4ec9-adfd-362ace5759d5.png)
confirmed working now.

**Comment by pippyn** [comment] 2022-06-23 09:21
Glad to see it's working. I'll close this issue now as this issue is referring to the old RD4 API.
If there are any new problems please open a new issue.

**Closed by pippyn** 2022-06-23 09:21 UTC
