### ISSUE TITLE
RecycleApp results unknown - connection error

### ISSUE THREAD

**Issue by tom-lejeune** [pippyn/Home-Assistant-Sensor-Afvalbeheer#321] opened 2022-06-28 12:51 UTC
Hi,
haven't changed anything in my setup but get error notification and results are "unknown"
```
  - platform: afvalbeheer
    wastecollector: RecycleApp 
    resources:                       
      - restafval
      - papier
      - pmd
      - glas
    postcode: 1700
    streetnumber: 17
    streetname: Libelstraat
    upcomingsensor: 1                
    dateformat: '%d-%m-%Y'           
    dateonly: 1
    dateobject: 0                   
    name: ''                        
    nameprefix: 1                  
    builtinicons: 0         
    disableicons: 0
    alwaysshowday: 1
    dutch: 1   
```

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1244
Integration: afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 14:34:39 (1 occurrences)
Last logged: 14:34:39

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa7b3bdf0>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by ghluhi** [comment] 2022-06-28 12:55
Have exactly the same issue and error for different address...

**Comment by pippyn** [comment] 2022-06-28 13:15
Hello, I've just tested your config on my test server and there the sensor is working fine. Maybe the API was down for a few minutes?

Could you try and reboot HA, once HA is fully started again wait a couple of minutes and see if the sensors are being populated again.

**Comment by tom-lejeune** [comment] 2022-06-28 14:16
thanks for helping , still the same result, will give it some time and try again tomorrow.

**Comment by Christophe999s** [comment] 2022-06-28 16:41
Same issue, tried rebooting, removing and re-adding the integration, but the error remains the same:

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1244
Integration: afvalbeheer (documentation)
First occurred: 18:39:50 (1 occurrences)
Last logged: 18:39:50

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0402d00c70>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by ghluhi** [comment] 2022-06-29 05:42
Tried several reboots, disabling pihole. Same error:

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1244
Integration: afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer))
First occurred: 07:37:35 (1 occurrences)
Last logged: 07:37:35

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f34b96c20a0>: Failed to establish a new connection: [Errno -3] Try again'))"))

Thx for looking into this.

**Comment by pippyn** [comment] 2022-06-29 06:10
I'm really not sure what's causing this as it works fine on my test machine.

What setup are you guys using? HA OS? HA core? VM? Docker?
What does your config of the sensor look like?

**Comment by sammyke007** [comment] 2022-06-29 06:11
HA OS 8.2 over here, latest core

**Comment by Christophe999s** [comment] 2022-06-29 06:14
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Running in a Proxmox VM

**Comment by M0nty99** [comment] 2022-06-29 07:05
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Running in docker on an ESXi VM

**Comment by tom-lejeune** [comment] 2022-06-29 07:36
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
Raspi 4

**Comment by Christophe999s** [comment] 2022-06-29 07:54
I'm getting a different error now:
This error originated from a custom integration.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1248
Integration: afvalbeheer (documentation)
First occurred: 09:43:02 (1 occurrences)
Last logged: 09:43:02

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/zipcodes?q=9230 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52e3e57eb0>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by pippyn** [comment] 2022-06-29 08:15
Thanks guys!

This confirms my suspicion that it is probably rate limiting on the API causing this issue.
The problem is that this is not easy to fix for me.

The only way to do "fix" this is setting the [update interval](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer#update-interval) really high, like `updateinterval: 48`. Reboot HA and check back again in 2 days. Yes days not hours, I'm sorry to say... If the sensor is working again you can lower the update interval to something like `updateinterval: 12` again (which will be the new default in the upcoming update v4.9.5), or remove the option to set the default interval.

**Comment by pippyn** [comment] 2022-06-29 08:19
You could try ofcourse, but as we don't know how the API limiting is configured I would set it really high.

**Comment by M0nty99** [comment] 2022-06-29 08:21
I've changed the option to 24 to start with. Thanks for the quick feedback @pippyn

**Comment by sammyke007** [comment] 2022-06-29 08:22
I've set it to 12, let's see...

**Comment by pippyn** [comment] 2022-06-29 08:23
I've just release [v4.9.5](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/releases/tag/v4.9.5) which sets the default interval to 12 hours.

**Comment by tom-lejeune** [comment] 2022-06-29 08:27
thanks a lot for your efforts Pippyn!  dank!

**Comment by sammyke007** [comment] 2022-06-29 08:28
Should we keep the new "test" code or is it already reverted because of the v4.9.5 update?

**Comment by pippyn** [comment] 2022-06-29 08:29
@sammyke007  If you update to the new version, the test code will be gone.

**Comment by Ravens28** [comment] 2022-06-29 08:31
Hi Pippyn,

I'm putting it on 48h... I don't see the need to update this information every 12h.
Afterall I suppose that the recycle companies doesn't change their planning everyday so with 48h it would be enough i think.

Thanks for your help and great work !

**Comment by pippyn** [comment] 2022-06-29 08:54
That could also be the issue for sure. The addresses I test with probably have another waste collector.

**Comment by XalaTheShepard** [comment] 2022-06-30 13:27
Is the integration based on the "ophaalkalender" or the Recycle app website? The website was down yesterday, but works fine now. The "Ophaalkalender" is still down and I very much doubt it will be back online soon as it seems they are implementing something new ...

**Comment by ydeschoe** [comment] 2022-06-30 18:46
after the upgrade to 4.9.5 I still have the same issue that the RycycleApp afvalbeheer intergration not working, still getting the API overflow error in my log files

This error originated from a custom integration.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1251
Integration: afvalbeheer (documentation)
First occurred: 20:41:51 (2 occurrences)
Last logged: 20:41:51

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc6bdb40580>: Failed to establish a new connection: [Errno -3] Try again'))"))
Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc6bdb520d0>: Failed to establish a new connection: [Errno -3] Try again'))"))

I have added now the updetinterval :48 to my config and restarted

**Comment by yornola** [comment] 2022-06-30 21:14
After some checks I found out that ophaalkalender.be is not working anymore but recycleapp.be is. Could it be that the API is referring to ophaalkalender and that this is the issue?

**Comment by bugzke** [comment] 2022-07-01 07:56
I am no Python coder unfortunately, but from what I can read from the code, it seems to call the right API (https://recycleapp.be/api/app/v1)

I can access the API via Postman, first getting an access token via https://recycleapp.be/api/app/v1/access-token and then doing a request to
https://recycleapp.be/api/app/v1/collections, giving me correct data.

But in HA same issue with the MaxRetryError on fetching the access token.

**Comment by Utopia69** [comment] 2022-07-01 08:54
Same problem (also after upgrade)
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1251
Integration: afvalbeheer (documentation)
First occurred: 00:12:34 (1 occurrences)
Last logged: 00:12:34

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72d2e730>: Failed to establish a new connection: [Errno -3] Try again'))"))

I also can get an access token trough Postman

**Comment by baaswietse** [comment] 2022-07-02 11:13
Hello, I have the same issue. All states return as "unknown".
On my other server which has an older install, there are no issues.

![image](https://user-images.githubusercontent.com/40791418/176998292-b50a2cd1-74e0-43c3-8d83-0979975cfafc.png)

**Comment by sammyke007** [comment] 2022-07-03 07:12
> Yes, but my [Domoticz LUA script](https://github.com/jvanderzande/GarbageCalendar) is still working fine AFAIK.
> 
> ![image](https://user-images.githubusercontent.com/33524412/176395081-df15a3bc-6566-4029-b8a5-8c60105be710.png)

Still running fine in Domoticz...
![image](https://user-images.githubusercontent.com/33524412/177029242-68702d87-57d3-4189-a68b-e7ed697fff3e.png)

**Comment by krism23** [comment] 2022-07-03 10:39
Also having the same issue. Updated, reinstalled but no luck.

Logger: custom_components.afvalbeheer.sensor
Source: custom_components/afvalbeheer/sensor.py:1251 
Integration: afvalbeheer ([documentation](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer)) 
First occurred: 2 juli 2022 23:05:01 (2 occurrences) 
Last logged: 11:05:06

Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6896ea3bb0>: Failed to establish a new connection: [Errno -3] Try again'))"))
Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f688d650d90>: Failed to establish a new connection: [Errno -3] Try again'))"))

**Comment by compunix-be** [comment] 2022-07-03 10:42
I had exact same issue: all 'unknown' and 'Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad210bb0>: Failed to establish a new connection: [Errno -3] Try again'))"))'

After some debugging and analysis, I discovered that HA was not able to resolve the name recycleapp.be
On my own computer, recycleapp.be was correctly resolved to an IP-address. Noticed that HA was able to resolve api.recycleapp.be

When I changed in /root/config/custom_components/afvalbeheer/sensor.py the main URL to the following:

self.main_url = 'https://api.recycleapp.be/api/app/v1/'

restarted, it is working again.

**Comment by editicalu** [comment] 2022-07-03 11:10
I can confirm that the fix proposed by @compunix-be is working. I'll make a PR so this is resolved as soon as possible.

**Comment by sammyke007** [comment] 2022-07-03 11:17
Line 1075 or 1152?

**Comment by bartdetre** [comment] 2022-07-04 08:23
The edit of line 1152 did the trick for me also!

**Comment by stevegit2022** [comment] 2022-07-04 09:30
> I had exact same issue: all 'unknown' and 'Error occurred while fetching data: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='recycleapp.be', port=443): Max retries exceeded with url: /api/app/v1/access-token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad210bb0>: Failed to establish a new connection: [Errno -3] Try again'))"))'
> 
> After some debugging and analysis, I discovered that HA was not able to resolve the name recycleapp.be On my own computer, recycleapp.be was correctly resolved to an IP-address. Noticed that HA was able to resolve api.recycleapp.be
> 
> When I changed in /root/config/custom_components/afvalbeheer/sensor.py the main URL to the following:
> 
> self.main_url = 'https://api.recycleapp.be/api/app/v1/'
> 
> restarted, it is working again.

Works now after this change. THANKS

**Comment by tom-lejeune** [comment] 2022-07-04 20:20
Yay!!!! Did the trick! Thanks y'all!!

**Comment by pippyn** [comment] 2022-07-05 06:53
Thanks guys!

I've tested the change and merged the PR. Version v4.9.6 of the sensor has the change implemented.

**Closed by pippyn** 2022-07-05 06:53 UTC

**Comment by M0nty99** [comment] 2022-07-05 17:53
Just wanted to confirm it is also working for me.

Thanks guys!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
