### ISSUE TITLE
Max retries exceeded for ROVA

### ISSUE THREAD

**Issue by kranendijk** [pippyn/Home-Assistant-Sensor-Afvalbeheer#501] opened 2024-08-25 09:27 UTC
Hi,

The Afvalbeheer indicates an “unkown” for the sensors. When I check the logfiles I see the error below. Is there something wron on ROVA side?
The Afvalbeheer had been working flawlessly until a few days ago. Home assistant, addon and HACS are all to the latest versions.

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalbeheer.API
Bron: custom_components/afvalbeheer/API.py:321
integratie: Afvalbeheer (documentatie)
Eerst voorgekomen: 11:22:26 (1 gebeurtenissen)
Laatst gelogd: 11:22:26

Error occurred while fetching data: SSLError(MaxRetryError("HTTPSConnectionPool(host='api.inzamelkalender.rova.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=8032TV&street=&huisnummer=30&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-08-25&langs=nl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))"))

**Comment by willemvnd** [comment] 2024-08-25 09:43
same here

**Comment by IGNWoudenberg** [comment] 2024-08-25 20:10
Here the same. SSL certificate seems not valid anymore on rova’s side?

**Comment by woytekbode** [comment] 2024-08-26 09:11
Same!

**Comment by kranendijk** [comment] 2024-08-26 09:41
Hi pippyn, for some reason I cannot copy and paste my config. Was able to make a printscreen though… hooe this helps?
![IMG_1794](https://github.com/user-attachments/assets/ef56b195-10f5-4472-824c-a6da5773cd21)

**Comment by pippyn** [comment] 2024-08-26 09:48
Yes the SSL certificate of the API end point is no longer valid. When ROVA fixes this issue, the sensor will work again.

**Comment by mr-brains** [comment] 2024-08-29 12:44
just had contact with ROVA, the person on the phone thinks it is no longer in use and will be terminated.
I think the person had no idea :-)  but promised to contact ICT.
now we Wait.

**Comment by mr-brains** [comment] 2024-08-29 13:42
> just had contact with ROVA, the person on the phone thinks it is no longer in use and will be terminated. I think the person had no idea :-) but promised to contact ICT. now we Wait.

they just phoned back, the certificate was never intended for public use, it will not be renewed.

**Comment by mr-brains** [comment] 2024-08-29 13:45
> I think they are right, because https://www.mijnafvalwijzer.nl/ no longer supports ROVA addresses according to my tests. Can you guys confirm? If so, i'll rewrite the ROVA integration to the new API.

confirmed, adres is resolved but "Uw adres is niet bekend bij ons. Klopt dit niet? Neem contact op met uw afvalinzamelaar"

the api i got from the logging was: https://api.inzamelkalender.rova.nl/webservices/appsinput/?apikey=string&method=postcodecheck&postcode=1234ab&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-08-29&langs=nl

**Comment by pippyn** [comment] 2024-08-29 13:53
I've rewritten the ROVA API in v5.3.10. Most likely it will create new entities when using this version.
Example config:
```
afvalbeheer:
  - wastecollector: ROVA
    resources:
      - GFT
      - Papier
      - PMD
    postcode: 8032TV
    streetnumber: 30
    upcomingsensor: 1
    dutch: 1
    printwastetypes: 1
```
Can you confirm this new version fixes the issues?

**Comment by mr-brains** [comment] 2024-08-29 15:22
Yes, i have the calendar back, and the entities have values again. I dont think they are new.

Thanks

**Comment by IGNWoudenberg** [comment] 2024-08-29 16:04
Yes, installed .10 version and did not had to do any config; works again with existing entities after reboot.

**Comment by willemvnd** [comment] 2024-08-29 16:45
Same here !!

Thanks very fast update

**Comment by kranendijk** [comment] 2024-08-29 17:34
It solved the issue, many many thanks!!!

**Comment by pippyn** [comment] 2024-08-30 06:34
Good to hear guys! I'll close this issue, if you have any problems/questions please open a new issue.

**Closed by pippyn** 2024-08-30 06:34 UTC
